# Generated by Django 4.0 on 2021-12-29 19:39

from django.db import migrations, models

import cobra.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_customuser_first_name_and_more"),
        ("project", "0005_rename_abstract_model_and_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="creator",
            field=models.ForeignKey(
                on_delete=models.SET(cobra.utils.models.get_default_admin),
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)s",
                to="user.customuser",
                verbose_name="creator",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="creator",
            field=models.ForeignKey(
                on_delete=models.SET(cobra.utils.models.get_default_admin),
                related_name="%(app_label)s_%(class)s_related",
                related_query_name="%(app_label)s_%(class)s",
                to="user.customuser",
                verbose_name="creator",
            ),
        ),
    ]
