# Generated by Django 4.0 on 2021-12-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_change_verbose_name_on_creator_field"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="slug_and_user_unique_constraint",
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("slug", "creator"), name="slug_and_creator_unique_constraint"
            ),
        ),
    ]
