# Generated by Django 4.0 on 2021-12-29 20:10

import django.db.models.deletion
from django.db import migrations, models

import cobra.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_customuser_first_name_and_more"),
        ("project", "0007_fix_user_slug_unique_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Epic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                ("title", models.CharField(max_length=250, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=models.SET(cobra.utils.models.get_default_admin),
                        related_name="%(app_label)s_%(class)s_related",
                        related_query_name="%(app_label)s_%(class)s",
                        to="user.customuser",
                        verbose_name="creator",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        related_query_name="%(app_label)s_%(class)s",
                        to="project.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="task",
            name="epic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="project.epic",
                verbose_name="related epic",
            ),
        ),
    ]
