version: "3"

services:
  db:
    image: postgres # use the latest official postgres version
    env_file:
      - ../.env/db.env # configure postgres
    ports:
      - "127.0.0.1:15432:5432" # map a port on the local machine to the port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data # persist data on the host machine even if the container gets destroyed.
    networks:
      - cobranet
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "5"

volumes:
  pgdata:

networks:
  cobranet:
