# Generated by Django 3.2.9 on 2021-11-07 01:13

from django.conf import settings
from django.db import IntegrityError, migrations


def create_default_admin(apps, schema_editor):
    CustomUser = apps.get_model("user", "CustomUser")
    try:
        CustomUser.objects.create_superuser(
            **getattr(settings, "DEFAULT_ADMIN_INFO", {})
        )
    except IntegrityError:
        pass


def delete_default_admin(apps, schema_editor):
    CustomUser = apps.get_model("user", "CustomUser")
    try:
        CustomUser.objects.delete(
            username=getattr(settings, "DEFAULT_ADMIN_INFO", {}).get("username", "")
        )
    except IntegrityError:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            code=create_default_admin,
            reverse_code=delete_default_admin,
        )
    ]
